from coinrun.Mask_RCNN.csci_e89_project import multi_class_instance_test_coinrun
from coinrun.Mask_RCNN.csci_e89_project.multi_class_instance_test_coinrun import detect_instance

detect_instance(inf_config.ALL_CLASS_NAMES, image_test_dir)